In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [6]:
df_occ = pd.read_csv("C:/Users/Nathan Vallet/Desktop/PROJET 3/data/raw/df_occ.csv", sep= ",", low_memory = False)

In [ ]:
csv_path = "C:/Users/Nathan Vallet/Desktop/PROJET 3/data/raw/df_occ_c.csv"
df_occ_c = df_occ.copy()
df_occ_c.to_csv(csv_path, index=False)

In [3]:
df_occ_c = pd.read_csv("C:/Users/Nathan Vallet/Desktop/PROJET 3/data/raw/df_occ_c.csv")

In [ ]:
------------------- NE PAS EXECUTER ----------------------

cols_to_keep = [
            'scientificName', 'decimalLatitude', 'decimalLongitude', 
            'eventDate', 'species', 'class', 'family', 'genus',
            'kingdom', 'phylum', 'order'
        ]

# HIERARCHIE DE CATEGORISATION (TAXONOMIE DU VIVANT): kingdom > phylum > class > order > family > genus > species
df_occ_c_reordered = df_occ_c.iloc[:, [0, 1, 2, 3, 8, 9, 5, 10, 6, 7, 4]]
df_occ_c = df_occ_c[df_occ_c['scientificName'].str.contains('BOLD', na=False) == False]
ou df_occ_c = df_occ_c[~df_occ_c['scientificName'].str.contains('BOLD', na=False)]

# NETTOYAGE EVENTDATE
df_occ_c_reordered['eventDate'] = df_occ_c_reordered['eventDate'].str.replace(r'T.*', '', regex=True)

In [23]:
df_occ_c[['order','kingdom']].describe()

                order   kingdom
count         7010223   7045064
unique            337         8
top     Passeriformes  Animalia
freq          3534299   6904316

In [24]:
df_occ_c[['species', 'class', 'family', 'genus', 'kingdom', 'phylum', 'order']].drop_duplicates().shape[0]

10584

In [29]:
df_occ_c[['species', 'class', 'family', 'genus', 'kingdom', 'phylum', 'order']].duplicated().sum()

7034480

In [ ]:
df_occ_c[df_occ_c[['species', 'class', 'family', 'genus', 'kingdom', 'phylum', 'order']].duplicated()]

In [27]:
df_occ_c.duplicated(subset=['species', 'class', 'family', 'genus', 'kingdom', 'phylum', 'order']).sum()

7034480

In [25]:
df_occ_c[['scientificName']].nunique()

scientificName    11364
dtype: int64

In [31]:
df_occ_c.head()

,scientificName,decimalLatitude,decimalLongitude,eventDate,species,class,family,genus,kingdom,phylum,order
0,"Coleophora Hübner, 1822",32.838000,-93.915000,2017-09-24,NaN,Insecta,Coleophoridae,Coleophora,Animalia,Arthropoda,Lepidoptera
1,BOLD:AAK7235,30.370903,-91.162094,2014-07-30,NaN,Insecta,Aphididae,Melanaphis,Animalia,Arthropoda,Hemiptera
2,BOLD:AAF5770,32.838000,-93.915000,2017-10-26,NaN,Insecta,Gelechiidae,Mesophleps,Animalia,Arthropoda,Lepidoptera
3,BOLD:AAK7235,29.756617,-90.812070,2014-07-28,NaN,Insecta,Aphididae,Melanaphis,Animalia,Arthropoda,Hemiptera
4,BOLD:AAK7235,30.458282,-91.140320,2014-07-30,NaN,Insecta,Aphididae,Melanaphis,Animalia,Arthropoda,Hemiptera

In [5]:
df_occ_c_reordered = df_occ_c.iloc[:, [0, 1, 2, 3, 8, 9, 5, 10, 6, 7, 4]]
df_occ_c_reordered.head()

,scientificName,decimalLatitude,decimalLongitude,eventDate,kingdom,phylum,class,order,family,genus,species
0,"Coleophora Hübner, 1822",32.838000,-93.915000,2017-09-24,Animalia,Arthropoda,Insecta,Lepidoptera,Coleophoridae,Coleophora,NaN
1,BOLD:AAK7235,30.370903,-91.162094,2014-07-30,Animalia,Arthropoda,Insecta,Hemiptera,Aphididae,Melanaphis,NaN
2,BOLD:AAF5770,32.838000,-93.915000,2017-10-26,Animalia,Arthropoda,Insecta,Lepidoptera,Gelechiidae,Mesophleps,NaN
3,BOLD:AAK7235,29.756617,-90.812070,2014-07-28,Animalia,Arthropoda,Insecta,Hemiptera,Aphididae,Melanaphis,NaN
4,BOLD:AAK7235,30.458282,-91.140320,2014-07-30,Animalia,Arthropoda,Insecta,Hemiptera,Aphididae,Melanaphis,NaN

In [44]:
df_occ_c_reordered['class'].value_counts()

class
Aves              6673612
Insecta            155945
Magnoliopsida      102069
Liliopsida          20671
Squamata            19092
                   ...
Cycadopsida             1
Tentaculata             1
Xanthophyceae           1
Megaviricetes           1
Glomeromycetes          1
Name: count, Length: 97, dtype: int64

In [50]:
df_occ_c = df_occ_c[df_occ_c['scientificName'].str.contains('BOLD', na=False) == False]
df_occ_c.head()

,scientificName,decimalLatitude,decimalLongitude,eventDate,species,class,family,genus,kingdom,phylum,order
0,"Coleophora Hübner, 1822",32.838,-93.915,2017-09-24,NaN,Insecta,Coleophoridae,Coleophora,Animalia,Arthropoda,Lepidoptera
6,"Coleotechnites Chambers, 1880",32.838,-93.915,2017-09-01,NaN,Insecta,Gelechiidae,Coleotechnites,Animalia,Arthropoda,Lepidoptera
7,"Coleotechnites Chambers, 1880",32.838,-93.915,2017-09-01,NaN,Insecta,Gelechiidae,Coleotechnites,Animalia,Arthropoda,Lepidoptera
8,"Leuctra Stephens, 1836",31.181,-92.565,2021-10-06,NaN,Insecta,Leuctridae,Leuctra,Animalia,Arthropoda,Plecoptera
11,"Leuctra Stephens, 1836",31.490,-93.099,2021-10-07,NaN,Insecta,Leuctridae,Leuctra,Animalia,Arthropoda,Plecoptera

In [6]:
df_occ_c_reordered = df_occ_c_reordered[df_occ_c_reordered['scientificName'].str.contains('BOLD', na=False) == False]
df_occ_c_reordered.head()

,scientificName,decimalLatitude,decimalLongitude,eventDate,kingdom,phylum,class,order,family,genus,species
0,"Coleophora Hübner, 1822",32.838,-93.915,2017-09-24,Animalia,Arthropoda,Insecta,Lepidoptera,Coleophoridae,Coleophora,NaN
6,"Coleotechnites Chambers, 1880",32.838,-93.915,2017-09-01,Animalia,Arthropoda,Insecta,Lepidoptera,Gelechiidae,Coleotechnites,NaN
7,"Coleotechnites Chambers, 1880",32.838,-93.915,2017-09-01,Animalia,Arthropoda,Insecta,Lepidoptera,Gelechiidae,Coleotechnites,NaN
8,"Leuctra Stephens, 1836",31.181,-92.565,2021-10-06,Animalia,Arthropoda,Insecta,Plecoptera,Leuctridae,Leuctra,NaN
11,"Leuctra Stephens, 1836",31.490,-93.099,2021-10-07,Animalia,Arthropoda,Insecta,Plecoptera,Leuctridae,Leuctra,NaN

In [11]:
df_occ_c_reordered.nunique()

scientificName       11348
decimalLatitude     325487
decimalLongitude    329783
eventDate           394212
kingdom                  8
phylum                  39
class                   97
order                  337
family                1310
genus                 5186
species               9534
dtype: int64

In [ ]:
import matplotlib.pyplot as plt

# Compter les occurrences de chaque kingdom
kingdom_counts = df_occ_c_reordered['kingdom'].value_counts()

# Tracer le bar chart
plt.figure(figsize=(10, 6))
kingdom_counts.plot(kind='bar')
plt.title('Répartition des observations par kingdom')
plt.xlabel('Kingdom')
plt.ylabel('Nombre d\'observations')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [2]:
###################### CHARGEMENT DU DF ######################

df_occ_c_reordered = pd.read_csv("C:/Users/Nathan Vallet/Desktop/PROJET 3/data/raw/df_occ_c_reordered.csv", sep= ",", low_memory = False)
df_occ_c_reordered.head()

,decimalLatitude,decimalLongitude,eventDate,kingdom,phylum,class,order,family,genus,species
0,32.838,-93.915,2017-09-24,Animalia,Arthropoda,Insecta,Lepidoptera,Coleophoridae,Coleophora,Coleophora Hbner
1,32.838,-93.915,2017-09-01,Animalia,Arthropoda,Insecta,Lepidoptera,Gelechiidae,Coleotechnites,Coleotechnites Chambers
2,32.838,-93.915,2017-09-01,Animalia,Arthropoda,Insecta,Lepidoptera,Gelechiidae,Coleotechnites,Coleotechnites Chambers
3,31.181,-92.565,2021-10-06,Animalia,Arthropoda,Insecta,Plecoptera,Leuctridae,Leuctra,Leuctra Stephens
4,31.490,-93.099,2021-10-07,Animalia,Arthropoda,Insecta,Plecoptera,Leuctridae,Leuctra,Leuctra Stephens

In [ ]:
# nettoyage eventDate #
df_occ_c_reordered['eventDate'] = df_occ_c_reordered['eventDate'].str.replace(r'T.*', '', regex=True)

In [3]:
# nettoyage eventDate 2#
df_occ_c_reordered['eventDate'] = df_occ_c_reordered['eventDate'].str.replace(r'/.*', '', regex=True)

In [3]:
# fonction avec regex pour nettoyer scientificName" #
def nettoyer_nom_scientifique(nom):
    if pd.isna(nom):
        return nom  # Garde les NaN

    # Supprimer les guillemets
    nom = nom.replace('"', '').replace("'", '')

    # Supprimer les contenus entre parenthèses (auteur, dates, etc.)
    nom = re.sub(r"\(.*?\)", "", nom)

    # Supprimer les abréviations type "L.", "Hüb." (majuscule + point)
    nom = re.sub(r"\b[A-Z]\.", "", nom)

    # Supprimer les années (4 chiffres consécutifs)
    nom = re.sub(r"\b\d{4}\b", "", nom)

    # Supprimer les virgules, points superflus, ou caractères non alphabétiques isolés
    nom = re.sub(r"[^a-zA-Z\s\-]", "", nom)

    # Réduire les espaces multiples à un seul
    nom = re.sub(r"\s+", " ", nom)

    # Enlever les espaces en début/fin
    nom = nom.strip()

    return nom

In [4]:
df_occ_c_reordered['scientificName'] = df_occ_c_reordered['scientificName'].apply(nettoyer_nom_scientifique)

In [ ]:
for _, rows in df_occ_c_reordered.iterrows():
    if rows["species"] == np.nan:
        rows["species"] = rows["scientificName"]

# Fonctionnel mais plus long

In [15]:
#df_occ_c_reordered.apply(lambda x: x["species"] if not np.nan else ["scientificName"])
df_occ_c_reordered = df_occ_c_reordered.copy()
df_occ_c_reordered["species"] = df_occ_c_reordered.apply(lambda x: x['species'] if not pd.isna(x['species']) else x['scientificName'], axis=1)

In [19]:
###### SUPPRESSION SCIENTIFICNAME ######

df_occ_c_reordered = df_occ_c_reordered.drop(["scientificName"], axis= 1)

#ou 

#df_occ_c_reordered.drop(columns=["scientificName"], inplace=True)

In [ ]:
df_occ_c_reordered.head(20)

In [4]:
#### SAUVEGARDE MODIF DF ####

csv_path = "C:/Users/Nathan Vallet/Desktop/PROJET 3/data/raw/df_occ_c_reordered.csv"
df_occ_c_reordered = df_occ_c_reordered.copy()
df_occ_c_reordered.to_csv(csv_path, index=False)