In [1]:
import pandas as pd

In [6]:
df_occ = pd.read_csv("C:/Users/Nathan Vallet/Desktop/PROJET 3/data/raw/df_occ.csv", sep= ",", low_memory = False)

In [ ]:
csv_path = "C:/Users/Nathan Vallet/Desktop/PROJET 3/data/raw/df_occ_c.csv"
df_occ_c = df_occ.copy()
df_occ_c.to_csv(csv_path, index=False)

In [ ]:
------------------- NE PAS EXECUTER ----------------------

cols_to_keep = [
            'scientificName', 'decimalLatitude', 'decimalLongitude', 
            'eventDate', 'species', 'class', 'family', 'genus',
            'kingdom', 'phylum', 'order'
        ]

# HIERARCHIE DE CATEGORISATION (TAXONOMIE DU VIVANT): kingdom > phylum > class > order > family > genus > species
df_occ_c_reordered = df_occ_c.iloc[:, [0, 1, 2, 3, 8, 9, 5, 10, 6, 7, 4]]
df_occ_c = df_occ_c[df_occ_c['scientificName'].str.contains('BOLD', na=False) == False]
ou df_occ_c = df_occ_c[~df_occ_c['scientificName'].str.contains('BOLD', na=False)]

In [14]:
df_occ_c.head(10)

,scientificName,decimalLatitude,decimalLongitude,eventDate,species,class,family,genus,kingdom,phylum,order
0,"Coleophora Hübner, 1822",32.838000,-93.915000,2017-09-24,NaN,Insecta,Coleophoridae,Coleophora,Animalia,Arthropoda,Lepidoptera
1,BOLD:AAK7235,30.370903,-91.162094,2014-07-30,NaN,Insecta,Aphididae,Melanaphis,Animalia,Arthropoda,Hemiptera
2,BOLD:AAF5770,32.838000,-93.915000,2017-10-26,NaN,Insecta,Gelechiidae,Mesophleps,Animalia,Arthropoda,Lepidoptera
3,BOLD:AAK7235,29.756617,-90.812070,2014-07-28,NaN,Insecta,Aphididae,Melanaphis,Animalia,Arthropoda,Hemiptera
4,BOLD:AAK7235,30.458282,-91.140320,2014-07-30,NaN,Insecta,Aphididae,Melanaphis,Animalia,Arthropoda,Hemiptera
5,BOLD:AAK7235,30.257694,-91.099270,2014-03-13,NaN,Insecta,Aphididae,Melanaphis,Animalia,Arthropoda,Hemiptera
6,"Coleotechnites Chambers, 1880",32.838000,-93.915000,2017-09-01,NaN,Insecta,Gelechiidae,Coleotechnites,Animalia,Arthropoda,Lepidoptera
7,"Coleotechnites Chambers, 1880",32.838000,-93.915000,2017-09-01,NaN,Insecta,Gelechiidae,Coleotechnites,Animalia,Arthropoda,Lepidoptera
8,"Leuctra Stephens, 1836",31.181000,-92.565000,2021-10-06,NaN,Insecta,Leuctridae,Leuctra,Animalia,Arthropoda,Plecoptera
9,BOLD:AAF0238,30.413000,-91.173000,2015-10-09,Polistes exclamans,Insecta,Eumenidae,Polistes,Animalia,Arthropoda,Hymenoptera

In [23]:
df_occ_c[['order','kingdom']].describe()

                order   kingdom
count         7010223   7045064
unique            337         8
top     Passeriformes  Animalia
freq          3534299   6904316

In [24]:
df_occ_c[['species', 'class', 'family', 'genus', 'kingdom', 'phylum', 'order']].drop_duplicates().shape[0]

10584

In [29]:
df_occ_c[['species', 'class', 'family', 'genus', 'kingdom', 'phylum', 'order']].duplicated().sum()

7034480

In [ ]:
df_occ_c[df_occ_c[['species', 'class', 'family', 'genus', 'kingdom', 'phylum', 'order']].duplicated()]

In [27]:
df_occ_c.duplicated(subset=['species', 'class', 'family', 'genus', 'kingdom', 'phylum', 'order']).sum()

7034480

In [25]:
df_occ_c[['scientificName']].nunique()

scientificName    11364
dtype: int64

In [31]:
df_occ_c.head()

,scientificName,decimalLatitude,decimalLongitude,eventDate,species,class,family,genus,kingdom,phylum,order
0,"Coleophora Hübner, 1822",32.838000,-93.915000,2017-09-24,NaN,Insecta,Coleophoridae,Coleophora,Animalia,Arthropoda,Lepidoptera
1,BOLD:AAK7235,30.370903,-91.162094,2014-07-30,NaN,Insecta,Aphididae,Melanaphis,Animalia,Arthropoda,Hemiptera
2,BOLD:AAF5770,32.838000,-93.915000,2017-10-26,NaN,Insecta,Gelechiidae,Mesophleps,Animalia,Arthropoda,Lepidoptera
3,BOLD:AAK7235,29.756617,-90.812070,2014-07-28,NaN,Insecta,Aphididae,Melanaphis,Animalia,Arthropoda,Hemiptera
4,BOLD:AAK7235,30.458282,-91.140320,2014-07-30,NaN,Insecta,Aphididae,Melanaphis,Animalia,Arthropoda,Hemiptera

In [ ]:
df_occ_c_reordered = df_occ_c.iloc[:, [0, 1, 2, 3, 8, 9, 5, 10, 6, 7, 4]]
df_occ_c_reordered.head()

In [44]:
df_occ_c_reordered['class'].value_counts()

class
Aves              6673612
Insecta            155945
Magnoliopsida      102069
Liliopsida          20671
Squamata            19092
                   ...
Cycadopsida             1
Tentaculata             1
Xanthophyceae           1
Megaviricetes           1
Glomeromycetes          1
Name: count, Length: 97, dtype: int64

In [50]:
df_occ_c = df_occ_c[df_occ_c['scientificName'].str.contains('BOLD', na=False) == False]
df_occ_c.head()

,scientificName,decimalLatitude,decimalLongitude,eventDate,species,class,family,genus,kingdom,phylum,order
0,"Coleophora Hübner, 1822",32.838,-93.915,2017-09-24,NaN,Insecta,Coleophoridae,Coleophora,Animalia,Arthropoda,Lepidoptera
6,"Coleotechnites Chambers, 1880",32.838,-93.915,2017-09-01,NaN,Insecta,Gelechiidae,Coleotechnites,Animalia,Arthropoda,Lepidoptera
7,"Coleotechnites Chambers, 1880",32.838,-93.915,2017-09-01,NaN,Insecta,Gelechiidae,Coleotechnites,Animalia,Arthropoda,Lepidoptera
8,"Leuctra Stephens, 1836",31.181,-92.565,2021-10-06,NaN,Insecta,Leuctridae,Leuctra,Animalia,Arthropoda,Plecoptera
11,"Leuctra Stephens, 1836",31.490,-93.099,2021-10-07,NaN,Insecta,Leuctridae,Leuctra,Animalia,Arthropoda,Plecoptera